services:
  redis:
    image: bitnami/redis:latest
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - app-network
  app:
    image: "ghcr.io/bootsie123/iconik-storage-migrator:latest"
    depends_on:
      - redis
    environment:
      ICONIK_APP_ID:
      ICONIK_TOKEN:
      NEW_STORAGE_ID:
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
