services:
  redis:
    image: bitnami/redis:latest
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6379:6379"
  app:
    build:
      context: ./
      target: development
    environment:
      ICONIK_APP_ID:
      ICONIK_TOKEN:
      NEW_STORAGE_ID:
      ADD_JOBS:
      REDIS_HOST: localhost
      REDIS_PORT:
      BULLMQ_PORT:
      BULLMQ_RESET_QUEUES:
      CONCURRENCY:
      DRY_RUN: true
    ports:
      - "3000:3000"

volumes:
  redis-data:
