services:
  redis:
    image: bitnami/redis:latest
    volumes:
      - redis_data:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - app-network
  app:
    build:
      context: ./
      target: development
    environment:
      ICONIK_APP_ID:
      ICONIK_TOKEN:
      NEW_STORAGE_ID:
      ADD_JOBS:
      REDIS_HOST: localhost
      REDIS_PORT:
      BULLMQ_PORT:
      BULLMQ_RESET_QUEUES:
      DRY_RUN: false
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
